### ISSUE TITLE
fmgd_firewall_policy - problem with creating policy

### ISSUE THREAD

**Issue by aopdal** [fortinet-ansible-dev/ansible-galaxy-fmgdevice-collection#3]
I'm trying to create a policy using the fmgd_firewall_policy module.

My playbook looks like this:

 name: Add policy
  hosts: fortimanager
  connection: httpapi
  gather_facts: false
  vars:
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    ansible_httpapi_port: 443
  tasks:
    - name: Configure policy
      fortinet.fmgdevice.fmgd_firewall_policy:
        access_token: xxxxx
        bypass_validation: true
        device: zzm-testfw01a
        vdom: CORP
        state: present
        firewall_policy:
          policyid: 10002
          name: test-policy2
          action: accept
          srcaddr:
            - ansible-test1
          srcintf: any
          dstaddr:
            - RFC1918-172
            - RFC1918-10
          dstintf: any
          service:
            - DNS
            - HTTP
          schedule: always
          status: enable
          logtraffic: all
          inspection_mode: flow
          auto_asic_offload: enable

The policy get created and I can get it using the facts module. But I can't see it in the UI of FortiManager and if I try to install it on the FortiGate it disapear.

If I create the policy with the playbook I may also delete it using Ansible by changing the state.

It is probably something I'm missing in my playbook, but I cant find it from the documentation.

I have created a topic here also : https://fndn.fortinet.net/index.php?/forums/topic/4413-fmgd_firewall_policy-problem-with-creating-policy/

**Comment by dux-fortinet** [comment]
Sorry for the confusion. 
The underlying API of FortiManager Device Ansible Collection (fmgd) and  FortiManager Ansible Collection (fmgr) are different.

You want to configure the FortiGate's policy through FortiManager. So I would recommend having a dedicated policy package in the FortiManager, adding policies to this package, and then installing this policy package.

Please try to use the **FortiManager Ansible Collection** to install the firewall policy. `fmgr_pkg_firewall_policy` is the module you need:
```
- name: Add policy
  hosts: fortimanager
  connection: httpapi
  gather_facts: false
  vars:
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    ansible_httpapi_port: 443
    adom: ansible74
    ppkg: FGVMMLTM23001325_root
  tasks:
    - name: Configure IPv4 policies.
      fortinet.fortimanager.fmgr_pkg_firewall_policy:
        adom: "{{adom}}" # The ADOM name where the device is located. If you haven't enabled multiple adoms, the default value should be root.
        pkg: "{{ppkg}}" # The package name where the policy will be added
        state: present
        pkg_firewall_policy:
          policyid: 10002
          name: test-policy2
          action: accept
          srcaddr:
            # - all
            - ansible-test1
          srcintf: any
          dstaddr: 
            # - all
            - RFC1918-172
            - RFC1918-10
          dstintf: any
          service:
            - DNS
            - HTTP
          schedule: always
          status: enable
          logtraffic: all
```

![Image](https://github.com/user-attachments/assets/eff93158-5c49-4a53-822c-5ae433f3a380)
And then, you can install this policy package, and the policies will be added to the device.
You can either install policy package through GUI:
![Image](https://github.com/user-attachments/assets/54eaaf48-b728-41a8-a46a-6458867031c2)
or install through Ansible:
```
- name: Install package
  hosts: fortimanager
  connection: httpapi
  gather_facts: false
  vars:
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    ansible_httpapi_port: 443
    adom: ansible74
    ppkg: FGVMMLTM23001325_root
    device: FGVMMLTM23001325
    vdom: root
  tasks:
    # Optional, bind the device to the policy package
    # - name: Add your {{ device }}-{{ vdom }} to pkg {{ ppkg }}
    #   fortinet.fortimanager.fmgr_pm_pkg_adom:
    #     adom: "{{ adom }}"
    #     pm_pkg_adom:
    #       name: "{{ ppkg }}"
    #       scope_member:
    #         - name: "{{ device }}"
    #           vdom: "{{ vdom }}"

    - name: Install for policy package [preview mode] {{ ppkg }}
      fortinet.fortimanager.fmgr_securityconsole_install_package:
        securityconsole_install_package:
          adom: "{{ adom }}"
          flags:
            - preview
          pkg: "{{ ppkg }}"
          scope:
            - name: "{{ device }}"
              vdom: "{{ vdom }}"
      register: r
    - name: Poll the task
      fortinet.fortimanager.fmgr_fact:
        facts:
          selector: "task_task"
          params:
            task: "{{ r.meta.response_data.task }}"
      register: taskinfo
      until: taskinfo.meta.response_data.percent == 100
      retries: 30
      delay: 5

    - name: Trigger the preview report generation for policy package {{ ppkg }}
      fortinet.fortimanager.fmgr_securityconsole_install_preview:
        securityconsole_install_preview:
          adom: "{{ adom }}"
          scope:
            - name: "{{ device }}"
              vdom: "{{ vdom }}"
          flags:
            - json
      register: r
    - name: Poll the task
      fortinet.fortimanager.fmgr_fact:
        facts:
          selector: "task_task"
          params:
            task: "{{ r.meta.response_data.task }}"
      register: taskinfo
      until: taskinfo.meta.response_data.percent == 100
      retries: 30
      delay: 5

    - name: Install package {{ ppkg }} to device from commit
      fortinet.fortimanager.fmgr_securityconsole_package_commit:
        securityconsole_package_commit:
          adom: "{{ adom }}"
          scope:
            - name: "{{ device }}"
              vdom: "{{ vdom }}"
      register: r
    - name: Poll the task
      fortinet.fortimanager.fmgr_fact:
        facts:
          selector: "task_task"
          params:
            task: "{{ r.meta.response_data.task }}"
      register: taskinfo
      until: taskinfo.meta.response_data.percent == 100
      retries: 30
      delay: 5
```

Then, the policies are installed in the FortiGate.

![Image](https://github.com/user-attachments/assets/e9807118-5615-4711-a870-253ac5dc3aa3)

Please let us know if you have any questions regarding the above playbooks.
Thanks,
Xinwei
